Add common films
Starcoffeman/java-filmorate pull request #26
Opened 2024-02-01 01:17 UTC by m777mm777

2024-02-01 16:37 UTC, maximboltinov requested changes

2024-02-01 16:37 UTC, maximboltinov commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorage.java
JOIN film_genre и genre нет необходимости, поскольку это реализовано в this::mapRowToFilm
f.RATING_ID в SELECT можно убрать достаточно r.ID AS MPA_ID

2024-02-01 16:37 UTC, maximboltinov commented on src/main/resources/schema.sql
Все же было бы лучше "подтянуть" изменения в develop и сделать rebase.

2024-02-01 16:37 UTC, maximboltinov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
Нет необходимости проверять наличие пользователя, поскольку это лишние запросы.
Проще перехватить исключение непосредственно при вызове
filmStorage.findCommonFilms(userId, friendId)
через try.. catch

2024-02-01 23:35 UTC, maximboltinov approved these changes

2024-02-01 23:37 UTC, maximboltinov approved these changes

2024-02-02 11:49 UTC, ValyGer approved these changes

2024-02-02 12:04 UTC, merged